#+title: Antero - writing
#+description: Personal website of Antero Mejr. Info and links to computer science publications,
#+description: scientific software, writing, etc.
#+INFOJS_OPT: view:info path:/org-info.js
#+options: toc:t title:t

* ICE cannot defeat student activism
:PROPERTIES:
:ID: ozturk
:END:
<2025-03-27 Thu>\\
Op-ed, published <2025-03-31 Mon> in [[https://www.tuftsdaily.com/article/2024/11/op-ed-institutional-neutrality-is-institutional-cowardice][The Tufts Daily]]

On Tuesday, masked federal agents in an unmarked vehicle [[https://www.tuftsdaily.com/article/2025/03/federal-authorities-detain-tufts-student-in-somerville][abducted]] Tufts
doctorate student Rümeysa Öztürk off the street in Somerville. She was
transported to a detention center in Louisiana, despite a court order ruling
that she be kept in Massachusetts. This incident not only presents a grave
physical danger to Tufts students but also a [[https://www.fire.org/research-learn/chilling-effect-overview][chilling effect]] on free speech as a
whole. The Tufts administration must take action to mitigate the impacts of
Immigration and Customs Enforcement's activities targeting Boston to ensure the
security of both U.S. citizens and international students.

An alleged cause for the detainment was [[https://www.tuftsdaily.com/article/2024/03/4ftk27sm6jkj][an op-ed]], coauthored by Öztürk,
published in the Daily last year. The article contains no references to violence
or terrorist groups, but after its publication, Öztürk was profiled by Canary
Mission, an anonymously operated website that works to suppress criticisms of
the Israeli state, the United States and Jewish individuals. The sequence of
events suggests that ICE may be using the website or similar data sources as a
guide to make arrests. This is a clear attack on the First Amendment protections
afforded to U.S. citizens and visa holders.

The Canary Mission site misleadingly discusses the terror group Hamas in their
post on Öztürk. However, Öztürk's public statement contains no references to
Hamas or related groups, and the most critical statement she makes about Israel,
besides calling on Tufts to acknowledge the Palestinian genocide, is approval of
the Boycott, Divestment and Sanctions movement. BDS, while unpopular with many
pro-Israel lobbyist groups, is nonviolent and asks for little beyond taking
economic action against the Israeli government for their noncompliance with
international laws. These are not extremist views: The United Nations Special
Rapporteur Francesca Albanese reported that there are "reasonable grounds" to
the claims of genocide, and the Norwegian sovereign wealth fund divested from
its shares in Israeli telecoms group Bezeq in 2024 since it provides services to
settlements in the West Bank.

The most important action Tufts - and other schools - should take is to check
Canary Mission and similar data sources and to reach out to students who are
targeted to ensure their safety and full [[https://www.tuftsdaily.com/article/2025/03/federal-judge-orders-rumeysa-ozturk-not-be-removed-from-united-states][protections provided]] by U.S. law. This
could include relocating the student or advising them to work remotely. These
efforts are perhaps the most effective way to immediately prevent the unlawful
detainments and relocations that ICE has been conducting in Boston over the past
two weeks. These sorts of hostile actions by political groups, both official and
unofficial, should be proactively de-risked as part of a campus security plan.
Tufts has experts in law, diplomacy and cybersecurity on staff; their input
would be valuable for this matter. Any existing "protocols" Tufts may have are
clearly insufficient, as last week's events have demonstrated.

Protests and rallies will do little to improve the safety of individuals and may
be harmful due to widespread surveillance from federal agencies and websites
that engage in doxxing. A comprehensive solution consisting of digital
intelligence, effective political messaging from universities and legal
constructs such as Boston's Trust Act is necessary to ensure the safety of
at-risk student populations, whether pro-Palestinian, pro-Israeli or any other
targeted group.

Take anti-free speech groups - they now not only exist in the context of the
Israel-Hamas conflict, but also proliferate as general right-wing
anti-Diversity, Equity and Inclusion groups. Their propaganda and doxxing
efforts must be countered directly, as the information space has become a key
battleground for social influence. Canary Mission accepts donations within the
United States and is not registered as an American nonprofit or a foreign agent.
If university-affiliated researchers were to expose the finances and membership
of these platforms, they could dampen attacks on students and researchers. When
dealing with shadowy online harassment groups, sunlight can be the best
disinfectant.

Universities have the resources to counter growing anti-intellectual sentiment,
but they are not using the tools they have to do so effectively. The specific
vehicle for attacks on academics - whether disguised as part of the Israel-Hamas
conflict, DEI, conservatism or immigration concerns - is irrelevant. If
universities do not ramp up efforts to prevent student harassment and
abductions, their influence will decline to negligible levels.

Losing Öztürk, whether permanently or temporarily, is a blow to maintaining a
wide array of viewpoints on campus. Ironically, if the worst case happens and
Öztürk is returned to Turkey, she would be returning at a time when Turkish
citizens are [[https://apnews.com/article/turkey-mayor-protest-ekrem-imamoglu-photo-gallery-1242ecc8c544f7368e9de326a0c5307a][practicing]] the same sort of activism that now must be practiced
[[https://www.tuftsdaily.com/article/2025/03/over-2000-protest-in-wake-of-student-detainment][on her behalf]]: pushing back against an unpopular, overreaching and expanding
autocracy.

It is obvious that ICE's actions will not improve American sentiment towards the
Israeli cause, nor will they help reach a tenable resolution of the conflicts in
the Middle East. That is not the intention. Rather, federal agencies are
currently being used as a cudgel to stoke fear and suppress public discourse,
shifting norms toward a Soviet-style self-censorship regime.

Institutions that value the American ideals of free speech, democracy and
justice will need to take action to prevent such an outcome. They should focus
on self-sufficiency, community initiatives and local entrepreneurship rather
than over-relying on federal grants and services. It would be immensely
disappointing if the Tufts administration prioritizes financial considerations
over student safety, making little or no meaningful change to prevent this sort
of incident from happening again.

Boston's students will be among the next generation of leaders in the political,
legal and business worlds. Their development will be stunted, however, if they
cannot write or speak due to fear of being arbitrarily terrorized by modern-day
goon squads, both online and on-campus. If their institutions do not protect
them, the coming decades of American history will not be characterized by
thoughtful governance. Instead, we will be subjected to ineffective
reactionaries, in a country ruled by fear.

* Institutional "neutrality" is institutional cowardice
:PROPERTIES:
:ID: neutrality
:END:
<2024-11-15 Fri>\\
Op-ed, published <2024-11-18 Mon> in [[https://www.tuftsdaily.com/article/2024/11/op-ed-institutional-neutrality-is-institutional-cowardice][The Tufts Daily]]

The Office of the Provost and Senior Vice President announced in an email to
students on Friday afternoon that Tufts is exploring the option of a
university-wide “Statement of Neutrality,” in which the university will attempt
to distance itself from “taking positions on geopolitical or social matters.”
Such an action would reflect poorly on the university, its administration, its
alumni and the students. It demonstrates the worst tendencies of current-day
institutions and should be opposed and scrapped for the following reasons.

It is unclear why such a policy is necessary in the first place. The incoming
presidential administration has proposed using federal funds as a [[https://apnews.com/article/trump-woke-education-24f864d83e2f5745d12a79ebac0d7cc4][bargaining
chip]] against universities, but Tufts' private status renders that irrelevant.
Still, neutrality policies set a precedent of schools' ideological choices being
dependent upon the whims of their funding sources. From that perspective, the
neutrality policy would advertise, in neon lights, that the university's ethics
are for sale to the highest bidder. Is Tufts' $69,000 tuition insufficient to
purchase a set of morals? Universities are supposed to be the vanguard for
societal progress and associated activism. How can students or alumni be proud
of a school that willingly gives that up for the sake of mild appeasement? And
make no mistake; such appeasement will not win the hearts and minds of
anti-intellectual people or leaders. Rather, it will be - correctly - perceived
as an example of elitist subterfuge.

The neutrality policy would also be shortsighted, as public consciousness
towards societal issues shifts with economic tides. When social issues are a
popular - and profitable - topic again, will the university quickly shuffle out
the neutrality policy for a non-neutrality policy? Recent election results are
not an indication that geopolitical or social issues are unimportant. Rather, it
reflects an unhappiness with current economic policy.

A neutrality policy would demonstrate that the university cannot or will not
perform the most basic of causal reasoning, which would be humiliating for an
institution engaged in policy research. For an example, look to the issue of
LGBTQ+ rights. LGBTQ+ computer scientists have made groundbreaking contributions
to the field and include visionaries like Lynn Conway and Alan Turing. A
regression of LGBTQ+ rights would result in worse outcomes for LGBTQ+ students,
diminishing their impact on computer science, Tufts' most popular major. Even if
the humanitarian aspect is dismissed, there is intrinsic value in taking a stand
for difficult or currently-unpopular causes. A neutrality policy would prevent
the university or faculty from opposing anti-LGBTQ+ policies of the incoming
presidential administration.

Neutrality constitutes a choice and is often the worst possible option. Take the
Israel-Hamas conflict. A neutral position would indicate tacit acceptance of the
status quo, where both Israeli and Palestinian civilians are killed for the sake
of the [[https://www.forbes.com/sites/dereksaul/2024/10/01/defense-stocks-hit-all-time-highs-amid-middle-east-escalation/][military-industrial complex]] and a select few political groups. If such a
status quo is maintained, the prospect of another decades-long war across the
Middle East seems inevitable. Sure, a neutral Tufts might receive grants for
researching weapons of war or other oppressive technologies that facilitate a
prolonged conflict. But, such "benefits" will be outweighed, in the long term,
by the unrealized opportunities of the lost generations of young Palestinians
and Israelis, including those who would make contributions to their field at
Tufts. Therefore, taking the side of finding a peaceful resolution would be a
sensible and non-neutral position to a difficult geopolitical situation. If a
neutrality policy were implemented, it would force the university and its staff
into taking a foolish, indifferent position on every possible issue in the
future.

There is a strong hypocrisy in having a Diversity, Equity, Inclusion and Justice
department and a "neutrality policy", as one precludes the other. Activism is a
core driver of progress when it comes to social issues and public policy. There
is no such thing as “neutral activism.” Both the U.S. and Tufts were born of the
milieu of the American Enlightenment, in which justice and humanitarianism were
core principles. Therefore, not only would a repressive neutrality policy be
hypocritical, it would also be un-American.

Also of note is the policy's announcement timing - a Friday after 2 p.m. This is
called the Friday news dump, used by political groups to bury bad news. If the
university knows the policy is bad news, then why is it being considered? The
answer: pursuit of short-term financial gains at the expense of the school's
reputation. It is not necessary to maximize quarterly gains when there is a $2.4
billion dollar endowment, high tuition and a constant stream of donations.
Rather, that financial cushion should empower the university to take a
courageous stand for long-term issues, beyond those of the four-year election
cycle.

Neutrality policies, by their very definition, restrain against the expression
of values. It will be impossible to enforce restraints non-selectively, as
activism and social issues are often unclear. The only possible result of such a
policy will be a mess of political battles, accusations and inquisitions which
will detract from the university's scholastic mission. The policy can only hurt
the university's mission, not help.

If the university does take a position of neutrality, I have just one request:
The statue of Jumbo should be replaced with one of a chicken. Elephants are
thoughtful, have a great memory of past history and look out for each other.
Chickens, by comparison, are greedy creatures, preoccupied with the pecking
order and abandon their young at the first sign of trouble. The neutrality
policy would demonstrate that the university's values correspond more closely
with the latter.
