* Institutional "neutrality" is institutional cowardice
:PROPERTIES:
:ID: neutrality
:END:
<2024-11-15 Fri>\\
Op-ed, published <2024-11-18 Mon> in [[https://www.tuftsdaily.com/article/2024/11/op-ed-institutional-neutrality-is-institutional-cowardice][The Tufts Daily]]

The Office of the Provost and Senior Vice President announced in an email to
students on Friday afternoon that Tufts is exploring the option of a
university-wide “Statement of Neutrality,” in which the university will attempt
to distance itself from “taking positions on geopolitical or social matters.”
Such an action would reflect poorly on the university, its administration, its
alumni and the students. It demonstrates the worst tendencies of current-day
institutions and should be opposed and scrapped for the following reasons.

It is unclear why such a policy is necessary in the first place. The incoming
presidential administration has proposed using federal funds as a [[https://apnews.com/article/trump-woke-education-24f864d83e2f5745d12a79ebac0d7cc4][bargaining
chip]] against universities, but Tufts' private status renders that irrelevant.
Still, neutrality policies set a precedent of schools' ideological choices being
dependent upon the whims of their funding sources. From that perspective, the
neutrality policy would advertise, in neon lights, that the university's ethics
are for sale to the highest bidder. Is Tufts' $69,000 tuition insufficient to
purchase a set of morals? Universities are supposed to be the vanguard for
societal progress and associated activism. How can students or alumni be proud
of a school that willingly gives that up for the sake of mild appeasement? And
make no mistake; such appeasement will not win the hearts and minds of
anti-intellectual people or leaders. Rather, it will be - correctly - perceived
as an example of elitist subterfuge.

The neutrality policy would also be shortsighted, as public consciousness
towards societal issues shifts with economic tides. When social issues are a
popular - and profitable - topic again, will the university quickly shuffle out
the neutrality policy for a non-neutrality policy? Recent election results are
not an indication that geopolitical or social issues are unimportant. Rather, it
reflects an unhappiness with current economic policy.

A neutrality policy would demonstrate that the university cannot or will not
perform the most basic of causal reasoning, which would be humiliating for an
institution engaged in policy research. For an example, look to the issue of
LGBTQ+ rights. LGBTQ+ computer scientists have made groundbreaking contributions
to the field and include visionaries like Lynn Conway and Alan Turing. A
regression of LGBTQ+ rights would result in worse outcomes for LGBTQ+ students,
diminishing their impact on computer science, Tufts' most popular major. Even if
the humanitarian aspect is dismissed, there is intrinsic value in taking a stand
for difficult or currently-unpopular causes. A neutrality policy would prevent
the university or faculty from opposing anti-LGBTQ+ policies of the incoming
presidential administration.

Neutrality constitutes a choice and is often the worst possible option. Take the
Israel-Hamas conflict. A neutral position would indicate tacit acceptance of the
status quo, where both Israeli and Palestinian civilians are killed for the sake
of the [[https://www.forbes.com/sites/dereksaul/2024/10/01/defense-stocks-hit-all-time-highs-amid-middle-east-escalation/][military-industrial complex]] and a select few political groups. If such a
status quo is maintained, the prospect of another decades-long war across the
Middle East seems inevitable. Sure, a neutral Tufts might receive grants for
researching weapons of war or other oppressive technologies that facilitate a
prolonged conflict. But, such "benefits" will be outweighed, in the long term,
by the unrealized opportunities of the lost generations of young Palestinians
and Israelis, including those who would make contributions to their field at
Tufts. Therefore, taking the side of finding a peaceful resolution would be a
sensible and non-neutral position to a difficult geopolitical situation. If a
neutrality policy were implemented, it would force the university and its staff
into taking a foolish, indifferent position on every possible issue in the
future.

There is a strong hypocrisy in having a Diversity, Equity, Inclusion and Justice
department and a "neutrality policy", as one precludes the other. Activism is a
core driver of progress when it comes to social issues and public policy. There
is no such thing as “neutral activism.” Both the U.S. and Tufts were born of the
milieu of the American Enlightenment, in which justice and humanitarianism were
core principles. Therefore, not only would a repressive neutrality policy be
hypocritical, it would also be un-American.

Also of note is the policy's announcement timing - a Friday after 2 p.m. This is
called the Friday news dump, used by political groups to bury bad news. If the
university knows the policy is bad news, then why is it being considered? The
answer: pursuit of short-term financial gains at the expense of the school's
reputation. It is not necessary to maximize quarterly gains when there is a $2.4
billion dollar endowment, high tuition and a constant stream of donations.
Rather, that financial cushion should empower the university to take a
courageous stand for long-term issues, beyond those of the four-year election
cycle.

Neutrality policies, by their very definition, restrain against the expression
of values. It will be impossible to enforce restraints non-selectively, as
activism and social issues are often unclear. The only possible result of such a
policy will be a mess of political battles, accusations and inquisitions which
will detract from the university's scholastic mission. The policy can only hurt
the university's mission, not help.

If the university does take a position of neutrality, I have just one request:
The statue of Jumbo should be replaced with one of a chicken. Elephants are
thoughtful, have a great memory of past history and look out for each other.
Chickens, by comparison, are greedy creatures, preoccupied with the pecking
order and abandon their young at the first sign of trouble. The neutrality
policy would demonstrate that the university's values correspond more closely
with the latter.
