* ICE cannot defeat student activism
:PROPERTIES:
:ID: ozturk
:END:
<2025-03-27 Thu>\\
Op-ed, published <2025-03-31 Mon> in [[https://www.tuftsdaily.com/article/2024/11/op-ed-institutional-neutrality-is-institutional-cowardice][The Tufts Daily]]

On Tuesday, masked federal agents in an unmarked vehicle [[https://www.tuftsdaily.com/article/2025/03/federal-authorities-detain-tufts-student-in-somerville][abducted]] Tufts
doctorate student Rümeysa Öztürk off the street in Somerville. She was
transported to a detention center in Louisiana, despite a court order ruling
that she be kept in Massachusetts. This incident not only presents a grave
physical danger to Tufts students but also a [[https://www.fire.org/research-learn/chilling-effect-overview][chilling effect]] on free speech as a
whole. The Tufts administration must take action to mitigate the impacts of
Immigration and Customs Enforcement's activities targeting Boston to ensure the
security of both U.S. citizens and international students.

An alleged cause for the detainment was [[https://www.tuftsdaily.com/article/2024/03/4ftk27sm6jkj][an op-ed]], coauthored by Öztürk,
published in the Daily last year. The article contains no references to violence
or terrorist groups, but after its publication, Öztürk was profiled by Canary
Mission, an anonymously operated website that works to suppress criticisms of
the Israeli state, the United States and Jewish individuals. The sequence of
events suggests that ICE may be using the website or similar data sources as a
guide to make arrests. This is a clear attack on the First Amendment protections
afforded to U.S. citizens and visa holders.

The Canary Mission site misleadingly discusses the terror group Hamas in their
post on Öztürk. However, Öztürk's public statement contains no references to
Hamas or related groups, and the most critical statement she makes about Israel,
besides calling on Tufts to acknowledge the Palestinian genocide, is approval of
the Boycott, Divestment and Sanctions movement. BDS, while unpopular with many
pro-Israel lobbyist groups, is nonviolent and asks for little beyond taking
economic action against the Israeli government for their noncompliance with
international laws. These are not extremist views: The United Nations Special
Rapporteur Francesca Albanese reported that there are "reasonable grounds" to
the claims of genocide, and the Norwegian sovereign wealth fund divested from
its shares in Israeli telecoms group Bezeq in 2024 since it provides services to
settlements in the West Bank.

The most important action Tufts - and other schools - should take is to check
Canary Mission and similar data sources and to reach out to students who are
targeted to ensure their safety and full [[https://www.tuftsdaily.com/article/2025/03/federal-judge-orders-rumeysa-ozturk-not-be-removed-from-united-states][protections provided]] by U.S. law. This
could include relocating the student or advising them to work remotely. These
efforts are perhaps the most effective way to immediately prevent the unlawful
detainments and relocations that ICE has been conducting in Boston over the past
two weeks. These sorts of hostile actions by political groups, both official and
unofficial, should be proactively de-risked as part of a campus security plan.
Tufts has experts in law, diplomacy and cybersecurity on staff; their input
would be valuable for this matter. Any existing "protocols" Tufts may have are
clearly insufficient, as last week's events have demonstrated.

Protests and rallies will do little to improve the safety of individuals and may
be harmful due to widespread surveillance from federal agencies and websites
that engage in doxxing. A comprehensive solution consisting of digital
intelligence, effective political messaging from universities and legal
constructs such as Boston's Trust Act is necessary to ensure the safety of
at-risk student populations, whether pro-Palestinian, pro-Israeli or any other
targeted group.

Take anti-free speech groups - they now not only exist in the context of the
Israel-Hamas conflict, but also proliferate as general right-wing
anti-Diversity, Equity and Inclusion groups. Their propaganda and doxxing
efforts must be countered directly, as the information space has become a key
battleground for social influence. Canary Mission accepts donations within the
United States and is not registered as an American nonprofit or a foreign agent.
If university-affiliated researchers were to expose the finances and membership
of these platforms, they could dampen attacks on students and researchers. When
dealing with shadowy online harassment groups, sunlight can be the best
disinfectant.

Universities have the resources to counter growing anti-intellectual sentiment,
but they are not using the tools they have to do so effectively. The specific
vehicle for attacks on academics - whether disguised as part of the Israel-Hamas
conflict, DEI, conservatism or immigration concerns - is irrelevant. If
universities do not ramp up efforts to prevent student harassment and
abductions, their influence will decline to negligible levels.

Losing Öztürk, whether permanently or temporarily, is a blow to maintaining a
wide array of viewpoints on campus. Ironically, if the worst case happens and
Öztürk is returned to Turkey, she would be returning at a time when Turkish
citizens are [[https://apnews.com/article/turkey-mayor-protest-ekrem-imamoglu-photo-gallery-1242ecc8c544f7368e9de326a0c5307a][practicing]] the same sort of activism that now must be practiced
[[https://www.tuftsdaily.com/article/2025/03/over-2000-protest-in-wake-of-student-detainment][on her behalf]]: pushing back against an unpopular, overreaching and expanding
autocracy.

It is obvious that ICE's actions will not improve American sentiment towards the
Israeli cause, nor will they help reach a tenable resolution of the conflicts in
the Middle East. That is not the intention. Rather, federal agencies are
currently being used as a cudgel to stoke fear and suppress public discourse,
shifting norms toward a Soviet-style self-censorship regime.

Institutions that value the American ideals of free speech, democracy and
justice will need to take action to prevent such an outcome. They should focus
on self-sufficiency, community initiatives and local entrepreneurship rather
than over-relying on federal grants and services. It would be immensely
disappointing if the Tufts administration prioritizes financial considerations
over student safety, making little or no meaningful change to prevent this sort
of incident from happening again.

Boston's students will be among the next generation of leaders in the political,
legal and business worlds. Their development will be stunted, however, if they
cannot write or speak due to fear of being arbitrarily terrorized by modern-day
goon squads, both online and on-campus. If their institutions do not protect
them, the coming decades of American history will not be characterized by
thoughtful governance. Instead, we will be subjected to ineffective
reactionaries, in a country ruled by fear.
